//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHGroupEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    //using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Data.Objects;
    
    public partial class BHGroupEntities : DbContext
    {
        public BHGroupEntities()
            : base("name=BHGroupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminLogin> AdminLogins { get; set; }
        public virtual DbSet<DrowToken> DrowTokens { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberPayroll> MemberPayrolls { get; set; }
        public virtual DbSet<PloatBooking> PloatBookings { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<vw_MemberDetail> vw_MemberDetail { get; set; }
        public virtual DbSet<vw_PlotBooking> vw_PlotBooking { get; set; }
    
        public virtual ObjectResult<Prc_ViewCommision_Result> Prc_ViewCommision(Nullable<int> parentId, string memberType)
        {
            var parentIdParameter = parentId.HasValue ?
                new ObjectParameter("ParentId", parentId) :
                new ObjectParameter("ParentId", typeof(int));
    
            var memberTypeParameter = memberType != null ?
                new ObjectParameter("MemberType", memberType) :
                new ObjectParameter("MemberType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Prc_ViewCommision_Result>("Prc_ViewCommision", parentIdParameter, memberTypeParameter);
        }
    }
}
