//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHGroupEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrowToken
    {
        public int DrowTokenId { get; set; }
        public int MemberId { get; set; }
        public string TokenNo { get; set; }
        public string Status { get; set; }
        public System.DateTime Creaton { get; set; }
        public Nullable<System.DateTime> Modifiedon { get; set; }
        public Nullable<int> PlotBookingId { get; set; }
    
        public virtual PloatBooking PloatBooking { get; set; }
        public virtual Member Member { get; set; }
    }
}
