//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHGroupEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Franchy
    {
        public int FranchiesId { get; set; }
        public string Name { get; set; }
        public int MemberShipNo { get; set; }
        public int ParentId { get; set; }
        public string Age { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Profession { get; set; }
        public string Address { get; set; }
        public string OfficeAddress { get; set; }
        public string PhoneNo_Office { get; set; }
        public string PhoneNo_Resident { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string PANNo { get; set; }
        public string NomineesName { get; set; }
        public string NomRelation { get; set; }
        public string NomAge { get; set; }
        public Nullable<System.DateTime> NomDOB { get; set; }
        public string NomProfession { get; set; }
        public string PreferredZone { get; set; }
        public string Password { get; set; }
        public Nullable<int> Intrest { get; set; }
        public string FrenchiesType { get; set; }
        public System.DateTime CreateOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Franchy Franchies1 { get; set; }
        public virtual Franchy Franchy1 { get; set; }
    }
}
