//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHGroupEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberPayroll
    {
        public int PaymentId { get; set; }
        public int MemberId { get; set; }
        public double Installment { get; set; }
        public double ReceiveAmt { get; set; }
        public double DueAmt { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatOn { get; set; }
        public System.DateTime ModifidOn { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public string PaymentType { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
