//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHGroupEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PloatToken
    {
        public int MemberTokenId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> Createon { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
