//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHGroupEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PlotBooking
    {
        public int PloatBookingId { get; set; }
        public string PloatType { get; set; }
        public string PlotDesc { get; set; }
        public int Qty { get; set; }
        public double Amt { get; set; }
        public double NetAmt { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int MemberId { get; set; }
        public string Name { get; set; }
        public int MemberShipNo { get; set; }
        public string Address { get; set; }
        public string PhoneNo_Office { get; set; }
    }
}
